port: 6001
# 加载的模型
check_point: weights/pt35.pth

# obs网盘配置
obs:
  ak: PRUSZLZORW5C7EBZICRM
  sk: Gxcv7At8SWR8cgmHcnsabeScnShc7BRXr1fHnGtZ
  server: https://obs.cn-southwest-2.myhuaweicloud.com
  bucket: telrobot
  base_dir: meta-human/results
  base_url: static.telrobot.top/

